### ISSUE TITLE
"masterPicture" in .favicon-data.json unaffected by custom image source path

### ISSUE THREAD

**Issue by CREEATION** [maliMirkec/starter-project-cli#1]
I've defined the custom image source path to `img`, but it generates as `gfx` in `gulpfile.js/.favicon-data.json` regardless.

**Comment by maliMirkec** [comment]
@CREEATION Thanks. I am going to work on this soon.

**Comment by maliMirkec** [comment]
@CREEATION I am sorry for the late response. I just tested the favicon task, and it works as expected. You might want to delete generated files to create new favicons. Delete both `gulpfile.js/.favicon-data-generated.json` file and `src/favicon` folder (or wherever you saved the favicon files), update the `gulpfile.js/.favicon-data.json` config and try to rerun Gulp. Let me know if that helps.

**Comment by maliMirkec** [comment]
I am closing this for lack of feedback.
